services:
  - type: web
    name: huggingface-image-gen-v2
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: HF_API_KEY
        sync: false
      - key: RENDER
        value: "true"
    healthCheckPath: /health
